language: ruby
sudo: false

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

script: "bundle exec rake clean spec cucumber"

addons:
  apt:
    packages:
    - ghostscript

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

matrix:
  fast_finish: true
  exclude:
    - gemfile: gemfiles/5.0.gemfile
      rvm: 2.1
    - gemfile: gemfiles/5.1.gemfile
      rvm: 2.1
    - gemfile: gemfiles/5.2.gemfile
      rvm: 2.1
    - gemfile: gemfiles/6.0.gemfile
      rvm: 2.1
    - gemfile: gemfiles/6.0.gemfile
      rvm: 2.2
    - gemfile: gemfiles/6.0.gemfile
      rvm: 2.3
    - gemfile: gemfiles/6.0.gemfile
      rvm: 2.4
